// Gravity → STEVE hand-off through Gravity's own engine (gravity-mcp), no Python port of the layout.
//
//   node gravity/handoff.mjs [knobs.json] [key=value ...] [--out steve/blowball_station/pod_layout.py]
//
// knobs.json is a Gravity snapshot (or any {key: value} object, or one with a `params` object); key=value
// arguments override it. The sim is stepped by gravity-mcp's run_sim until the layout has relaxed, and its data
// block (particles 0..128, see DATA in blowball_station.js) is read back and written as a data-only Python module:
// DIRS (unit vectors, STEVE frame: Z = docking axis) and ORDER (assembly sequence).
//
// The server is started with npx from holodeck1.ai unless GRAVITY_MCP points at a local server.mjs.
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const PKG = 'https://holodeck1.ai/mcp/gravity-mcp-0.2.0.tgz';
const HERE = path.dirname(new URL(import.meta.url).pathname);
const SIM = path.join(HERE, 'blowball_station.js');
const MAXP = 64, ITERS = 1200, PER_FRAME = 6;              // keep in sync with blowball_station.js

// ---- arguments ----
let knobs = {}, out = path.join(HERE, '..', 'steve', 'blowball_station', 'pod_layout.py');
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--out') out = argv[++i];
  else if (a.includes('=')) { const [k, v] = a.split('='); knobs[k] = Number(v); }
  else { const j = JSON.parse(fs.readFileSync(a, 'utf8')); Object.assign(knobs, j.params ?? j); }
}

// ---- a minimal stdio MCP client ----
const cmd = process.env.GRAVITY_MCP ? ['node', [process.env.GRAVITY_MCP]] : ['npx', ['-y', `--package=${PKG}`, 'gravity-mcp']];
const srv = spawn(cmd[0], cmd[1], { stdio: ['pipe', 'pipe', 'inherit'] });
let buf = '', id = 0;
const pending = new Map();
srv.stdout.on('data', (d) => {
  buf += d;
  for (let i; (i = buf.indexOf('\n')) >= 0;) {
    const line = buf.slice(0, i); buf = buf.slice(i + 1);
    if (!line.trim()) continue;
    const m = JSON.parse(line);
    pending.get(m.id)?.(m); pending.delete(m.id);
  }
});
const rpc = (method, params) => new Promise((resolve) => {
  pending.set(++id, resolve);
  srv.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n');
});
const tool = async (name, args) => {
  const m = await rpc('tools/call', { name, arguments: args });
  const text = m.result?.content?.find((c) => c.type === 'text')?.text;
  if (m.error || m.result?.isError) throw new Error(`${name}: ${text ?? JSON.stringify(m.error)}`);
  return JSON.parse(text);
};

try {
  await rpc('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'steveVgravity-handoff', version: '1' } });
  srv.stdin.write(JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }) + '\n');

  // ---- run the sim and read the data block ----
  const source = fs.readFileSync(SIM, 'utf8');
  const r = await tool('run_sim', {
    source, params: knobs, steps: Math.ceil(ITERS / PER_FRAME) + 10,
    particleCount: 5000, sample: 5000, timeLimitSeconds: 60,
  });
  if (r.stoppedEarly || r.stepsDone < Math.ceil(ITERS / PER_FRAME)) throw new Error(`run_sim stopped early: ${JSON.stringify(r).slice(0, 300)}`);
  const P = r.sample;
  const [hx, hy] = P[2 * MAXP];
  const n = Math.round(hx * 100), progress = hy * 2;
  if (progress < 1) throw new Error(`layout not relaxed yet (${(progress * 100).toFixed(1)} %)`);

  const unit = ([x, y, z]) => { const m = Math.hypot(x, y, z); return [x / m, y / m, z / m]; };
  const toSteve = ([x, y, z]) => [x, -z, y];               // Gravity y-up → STEVE z-up (as blowball_layout.to_steve)
  const dirs = P.slice(0, n).map(unit);
  const order = P.slice(MAXP, MAXP + n).map((p) => {     // match each launch's direction back to a pod index
    const u = unit(p);
    let best = -1, bd = Infinity;
    dirs.forEach((d, q) => { const e = Math.hypot(d[0] - u[0], d[1] - u[1], d[2] - u[2]); if (e < bd) { bd = e; best = q; } });
    if (bd > 1e-3) throw new Error(`launch direction matches no pod (error ${bd})`);
    return best;
  });
  if (new Set(order).size !== n) throw new Error(`ORDER is not a permutation: ${order}`);

  // ---- write the data module ----
  const f = (v) => v.toFixed(5).padStart(9);
  const used = Object.fromEntries(Object.entries(knobs).sort());
  const py = `# Generated by gravity/handoff.mjs from Gravity's own engine (gravity-mcp run_sim). Do not edit.
# Knobs: ${JSON.stringify(used)}
# Pods: ${n}; layout relaxed ${(progress * 100).toFixed(0)} %; directions read at 4-decimal precision (~1e-4).
N = ${n}
DIRS = [   # unit vectors, STEVE frame (Z = docking axis); DIRS[0] = pod 0
${dirs.map((d) => `    (${toSteve(d).map(f).join(', ')}),`).join('\n')}
]
ORDER = ${JSON.stringify(order)}   # pod flown at each launch; ORDER[0] = 0 flies with the hub
`;
  fs.writeFileSync(out, py);
  console.log(`wrote ${out}: ${n} pods, order ${order.join(' ')}`);
} finally {
  srv.kill();
}
